#!/bin/sh

echo '<<<nut>>>'

if which upsc > /dev/null 2>&1 ; then
    for ups in $(upsc -l > /dev/stdout 2> /dev/null)
    do
        upsc $ups > /dev/stdout 2> /dev/null | sed "s,^,$ups ,"
    done
else
    echo "ERROR: upsc not found" >&2
fi
